# Counterbalance check controller moves arm to different positions
cb_check_controller: &cb_check_controller_base
  type: CounterbalanceTestController
  settle_time: 2.0
  dither_points: 1000
  timeout: 300
  screw_tol: 2.0
  bar_tol: 0.8
  lift:
    joint: r_shoulder_lift_joint
    type: JointPositionController
    pid/p: 80.0
    pid/i: 8.0
    pid/d: 6.0
    pid/i_clamp: 3.0
    min: -0.2
    max: 1.21
    delta: 0.2
    dither: 8.0
    mse: 3.0
    avg_abs: 2.0
    avg_eff: 1.5
  flex:
    joint: r_elbow_flex_joint
    type: JointPositionController
    pid/p: 70.0
    pid/d: 12.0
    pid/i: 12.0
    pid/i_clamp: 2.0
    min: -1.8
    max: -0.19
    delta: 0.2
    dither: 6.0
    mse: 3.0
    avg_abs: 2.0
    avg_eff: 1.5

# Right side
cb_right_controller: 
  <<: *cb_check_controller_base
  lift:
    joint: r_shoulder_lift_joint
  flex:
    joint: r_elbow_flex_joint

# Left side
cb_left_controller: 
  <<: *cb_check_controller_base
  lift:
    joint: l_shoulder_lift_joint
  flex:
    joint: l_elbow_flex_joint
